// Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.

const solution = () => {
	let num1 = 1
	let num2 = 2
	let sum = num2
	while (num2 < 4000000) {
		let nextNum = num1 + num2
		if (nextNum > 4000000) break

		if (nextNum % 2 === 0) sum += nextNum
		num1 = num2
		num2 = nextNum
	}
	return sum
}

export default solution

export const solved: boolean = true

